// Generated by scripts/build-starter-curriculum.mjs — do not edit by hand.
export const aiStarterCurriculum = {
  "topics": [
    {
      "slug": "fundamentals",
      "title": "მოდული 1 — Prompting-ის საფუძვლები",
      "lessons": [
        {
          "slug": "intro",
          "title": "AI კურსის შესავალი",
          "videoId": "K3uu30qJFmo",
          "seconds": 527
        },
        {
          "slug": "at-work",
          "title": "AI სამუშაოში",
          "videoId": "ykIH3Inso8M",
          "seconds": 55
        },
        {
          "slug": "what-is-prompting",
          "title": "რა არის Prompting?",
          "videoId": "uSUbJvCaznY",
          "seconds": 189
        },
        {
          "slug": "overview",
          "title": "კურსის მიმოხილვა",
          "videoId": "ESBk7mlUhjo",
          "seconds": 374
        },
        {
          "slug": "planning",
          "title": "Planning — დაგეგმვა",
          "videoId": "wROtJ69SBII",
          "seconds": 149
        },
        {
          "slug": "framework-step1",
          "title": "Framework ნაბიჯი 1: Task, Persona, Format",
          "videoId": "BLFbJRJtd38",
          "seconds": 462
        },
        {
          "slug": "context-theory",
          "title": "კონტექსტი — თეორია",
          "videoId": "2ubsDImfqN0",
          "seconds": 221
        },
        {
          "slug": "context-practice",
          "title": "კონტექსტი — პრაქტიკა",
          "videoId": "GJ2MwupkSHA",
          "seconds": 397
        },
        {
          "slug": "references-theory",
          "title": "References — თეორია",
          "videoId": "_LbKKBomqFk",
          "seconds": 157
        },
        {
          "slug": "references-practice",
          "title": "References — პრაქტიკა",
          "videoId": "04u3M_Nx-e4",
          "seconds": 343
        },
        {
          "slug": "shots",
          "title": "Few-Shot მაგალითები (Shots)",
          "videoId": "KC0cDXnu97Q",
          "seconds": 849
        },
        {
          "slug": "evaluate",
          "title": "შეფასება (Evaluate)",
          "videoId": "FHA9x7C6oXI",
          "seconds": 783
        },
        {
          "slug": "iterate",
          "title": "Iterate — გამეორება",
          "videoId": "8kNcblkARVg",
          "seconds": 918
        },
        {
          "slug": "tcrei-model",
          "title": "T.C.R.E.I. მოდელი (პრაქტიკა)",
          "videoId": "meGlYoD5ndc",
          "seconds": 1329
        }
      ]
    },
    {
      "slug": "practice",
      "title": "მოდული 2 — პრაქტიკული შაბლონები და მონაცემები",
      "lessons": [
        {
          "slug": "auto-plan-template",
          "title": "ავტომატური გეგმის შაბლონი",
          "videoId": "vh50xos74E0",
          "seconds": 1669
        },
        {
          "slug": "complex-concept-template",
          "title": "რთული კონცეფციის ახსნის შაბლონი",
          "videoId": "w0YIFZvigic",
          "seconds": 929
        },
        {
          "slug": "youtube-script-template",
          "title": "YouTube ვიდეოს სცენარის შაბლონი",
          "videoId": "7TmnsnU_t9w",
          "seconds": 570
        },
        {
          "slug": "research-practice",
          "title": "AI კვლევის ჩატარების შაბლონი",
          "videoId": "C2hZCCxPNIw",
          "seconds": 821
        },
        {
          "slug": "cot-intro",
          "title": "Advanced Prompting: Chain of Thought",
          "videoId": "hFrB7AO4nuM",
          "seconds": 916
        },
        {
          "slug": "prompt-chaining",
          "title": "პრომპტების ჯაჭვი (Prompt Chaining)",
          "videoId": "IpKBqDvIEI0",
          "seconds": 894
        },
        {
          "slug": "data-processing-intro",
          "title": "მონაცემების დამუშავება — შესავალი",
          "videoId": "90Ynf1k-_UI",
          "seconds": 941
        },
        {
          "slug": "table-data-part2",
          "title": "ცხრილური მონაცემები (ნაწილი 2)",
          "videoId": "j7Dv5OgWgQc",
          "seconds": 1160
        },
        {
          "slug": "csv",
          "title": "CSV ფორმატი",
          "videoId": "6B315r3t0Aw",
          "seconds": 750
        },
        {
          "slug": "markdown",
          "title": "Markdown ფორმატი",
          "videoId": "-N7UwqDQ8iw",
          "seconds": 670
        },
        {
          "slug": "json",
          "title": "JSON — ფორმატების მეფე",
          "videoId": "YvtRgvW4K10",
          "seconds": 1215
        }
      ]
    },
    {
      "slug": "customer-profile",
      "title": "მოდული 3 — პროდუქტიულობა და ბიზნესი",
      "lessons": [
        {
          "slug": "ideal-customer-persona",
          "title": "იდეალური მომხმარებლის პერსონა: პროფილის შექმნა",
          "videoId": "AqZlyaVWkXg",
          "seconds": 1046
        },
        {
          "slug": "brand-voice-guide",
          "title": "ბრენდის ხმის სახელმძღვანელოს შექმნა",
          "videoId": "7L-5rVDV_gE",
          "seconds": 941
        },
        {
          "slug": "synthesis-audience-brand-voice",
          "title": "სინთეზი — აუდიტორია + ბრენდის ხმა",
          "videoId": "sEIq_qNYick",
          "seconds": 1151
        },
        {
          "slug": "notebooklm-central-hub",
          "title": "NotebookLM - ის გამოყენება ცენტრალური ჰაბის შესაქმნელად",
          "videoId": "PqYK-h3eiPA",
          "seconds": 2322
        },
        {
          "slug": "brainstorming-idea-generation",
          "title": "იდეების ავტომატური გენერაცია - ბრეინშტორმინგი",
          "videoId": "9ed5YF_s92k",
          "seconds": 602
        },
        {
          "slug": "content-calendar-practice",
          "title": "კონტენტის კალენდარი პრაქტიკაში",
          "videoId": "hCD_mNhkzww",
          "seconds": 985
        }
      ]
    }
  ]
};
